#====================================================================================================================================================================================
Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 1800
#===============#
# Centos7 Nodes #
#===============#

#Ansible-Node01
  config.vm.define "ansible-node01" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Node01"
      vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
      vb.cpus = 2
      vb.memory = 1024
    end
    cfg.vm.host_name = "ansible-node01"
    cfg.vm.network "private_network", ip: "192.168.56.101"
    cfg.vm.network "forwarded_port", guest:22, host:60101, auto_correct: true, id: "ssh"
    cfg.vm.network "forwarded_port", guest:80, host:60081, auto_correct: true
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", path:"bash_ssh_conf_4_CentOS.sh"
  end

#Ansible-Node02
  config.vm.define "ansible-node02" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Node02"
      vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
      vb.cpus = 2
      vb.memory = 1024
    end
    cfg.vm.host_name = "ansible-node02"
    cfg.vm.network "private_network", ip: "192.168.56.102"
    cfg.vm.network "forwarded_port", guest:22, host:60102, auto_correct: true, id: "ssh"
    cfg.vm.network "forwarded_port", guest:80, host:60082, auto_correct: true
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", path:"bash_ssh_conf_4_CentOS.sh"
  end

#Ansible-Node03
  config.vm.define "ansible-node03" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Node03"
      vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
      vb.cpus = 2
      vb.memory = 1024
    end
    cfg.vm.host_name = "ansible-node03"
    cfg.vm.network "private_network", ip: "192.168.56.103"
    cfg.vm.network "forwarded_port", guest:22, host:60103, auto_correct: true, id: "ssh"
    cfg.vm.network "forwarded_port", guest:80, host:60083, auto_correct: true
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", path:"bash_ssh_conf_4_CentOS.sh"
  end

#==============#
# Ubuntu nodes #
#==============#
  
#Ansible-Node04
  config.vm.define "ansible-node04" do |cfg|
    cfg.vm.box = "ubuntu/trusty64"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Node04"
      vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
      vb.cpus = 2
      vb.memory = 1024
    end
    cfg.vm.host_name = "ansible-node04"
    cfg.vm.network "private_network", ip: "192.168.56.201"
    cfg.vm.network "forwarded_port", guest: 22, host: 60201, auto_correct: true, id: "ssh"
    cfg.vm.network "forwarded_port", guest:80, host:60084, auto_correct: true
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
  end
 
#Ansible-Node05	 
  config.vm.define "ansible-node05" do |cfg|
    cfg.vm.box = "ubuntu/trusty64"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Node05"
      vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
      vb.cpus = 2
      vb.memory = 1024
    end
    cfg.vm.host_name = "ansible-node05"
    cfg.vm.network "private_network", ip: "192.168.56.202"
    cfg.vm.network "forwarded_port", guest: 22, host: 60202, auto_correct: true, id: "ssh"
    cfg.vm.network "forwarded_port", guest:80, host:60085, auto_correct: true
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
  end

#Ansible-Node06	 
  config.vm.define "ansible-node06" do |cfg|
    cfg.vm.box = "ubuntu/trusty64"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Node06"
      vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
      vb.cpus = 2
      vb.memory = 1024
    end
    cfg.vm.host_name = "ansible-node06"
    cfg.vm.network "private_network", ip: "192.168.56.203"
    cfg.vm.network "forwarded_port", guest: 22, host: 60203, auto_correct: true, id: "ssh"
    cfg.vm.network "forwarded_port", guest:80, host:60086, auto_correct: true
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true 
  end
#===============#
#Ansible Server #
#===============#

#Ansible Server01
  config.vm.define "ansible-server" do |cfg|
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Server"
      vb.customize ["modifyvm", :id, "--groups", "/Ansible"]
      vb.cpus = 2
      vb.memory = 1024
    end
    cfg.vm.host_name = "ansible-server"
    cfg.vm.network "private_network", ip: "192.168.56.10"
    cfg.vm.network "forwarded_port", guest:22, host:60010, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", inline:"yum install epel-release -y"
    cfg.vm.provision "shell", inline:"yum install ansible -y"
    cfg.vm.provision "file", source: "ansible_env_ready.yml", 
	    destination: "ansible_env_ready.yml"
	  cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
    cfg.vm.provision "file", source: "auto_pass.yml", destination: "auto_pass.yml"
    cfg.vm.provision "shell", inline: "ansible-playbook auto_pass.yml", privileged: false
  end

#====================================================================================================================================================================================
end